# Site settings
title: PDX Hackerspace
email: jon@ctrlh.org
url: http://pdxhackerspace.org
description: "Portland's Hackerspace. North Portland's place for tinkering, making, and hacking."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: PDX Hackerspace
  location: Portland, Oregon
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ctrlhpdx
  - title: facebook
    url: http://facebook.com/ctrlhpdx
  - title: github
    url: http://github.com/ctrlh

# Postal address (add as many lines as necessary)
address:
  - line: 7608 N Interstate
  - line: Portland, OR 97217
  
# Credits content
credits: 'Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
